// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: fraud_service.proto
#ifndef GRPC_fraud_5fservice_2eproto__INCLUDED
#define GRPC_fraud_5fservice_2eproto__INCLUDED

#include "fraud_service.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace fraudservice {

class FraudDetectService final {
 public:
  static constexpr char const* service_full_name() {
    return "fraudservice.FraudDetectService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Transact(::grpc::ClientContext* context, const ::fraudservice::TransactRequest& request, ::fraudservice::TransactReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fraudservice::TransactReply>> AsyncTransact(::grpc::ClientContext* context, const ::fraudservice::TransactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fraudservice::TransactReply>>(AsyncTransactRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fraudservice::TransactReply>> PrepareAsyncTransact(::grpc::ClientContext* context, const ::fraudservice::TransactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fraudservice::TransactReply>>(PrepareAsyncTransactRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Transact(::grpc::ClientContext* context, const ::fraudservice::TransactRequest* request, ::fraudservice::TransactReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Transact(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fraudservice::TransactReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Transact(::grpc::ClientContext* context, const ::fraudservice::TransactRequest* request, ::fraudservice::TransactReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void Transact(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fraudservice::TransactReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fraudservice::TransactReply>* AsyncTransactRaw(::grpc::ClientContext* context, const ::fraudservice::TransactRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fraudservice::TransactReply>* PrepareAsyncTransactRaw(::grpc::ClientContext* context, const ::fraudservice::TransactRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Transact(::grpc::ClientContext* context, const ::fraudservice::TransactRequest& request, ::fraudservice::TransactReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fraudservice::TransactReply>> AsyncTransact(::grpc::ClientContext* context, const ::fraudservice::TransactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fraudservice::TransactReply>>(AsyncTransactRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fraudservice::TransactReply>> PrepareAsyncTransact(::grpc::ClientContext* context, const ::fraudservice::TransactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fraudservice::TransactReply>>(PrepareAsyncTransactRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Transact(::grpc::ClientContext* context, const ::fraudservice::TransactRequest* request, ::fraudservice::TransactReply* response, std::function<void(::grpc::Status)>) override;
      void Transact(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fraudservice::TransactReply* response, std::function<void(::grpc::Status)>) override;
      void Transact(::grpc::ClientContext* context, const ::fraudservice::TransactRequest* request, ::fraudservice::TransactReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void Transact(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::fraudservice::TransactReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::fraudservice::TransactReply>* AsyncTransactRaw(::grpc::ClientContext* context, const ::fraudservice::TransactRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fraudservice::TransactReply>* PrepareAsyncTransactRaw(::grpc::ClientContext* context, const ::fraudservice::TransactRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Transact_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Transact(::grpc::ServerContext* context, const ::fraudservice::TransactRequest* request, ::fraudservice::TransactReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Transact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Transact() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Transact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Transact(::grpc::ServerContext* context, const ::fraudservice::TransactRequest* request, ::fraudservice::TransactReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTransact(::grpc::ServerContext* context, ::fraudservice::TransactRequest* request, ::grpc::ServerAsyncResponseWriter< ::fraudservice::TransactReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Transact<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Transact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_Transact() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::fraudservice::TransactRequest, ::fraudservice::TransactReply>(
          [this](::grpc::ServerContext* context,
                 const ::fraudservice::TransactRequest* request,
                 ::fraudservice::TransactReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->Transact(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_Transact(
        ::grpc::experimental::MessageAllocator< ::fraudservice::TransactRequest, ::fraudservice::TransactReply>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::fraudservice::TransactRequest, ::fraudservice::TransactReply>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Transact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Transact(::grpc::ServerContext* context, const ::fraudservice::TransactRequest* request, ::fraudservice::TransactReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Transact(::grpc::ServerContext* context, const ::fraudservice::TransactRequest* request, ::fraudservice::TransactReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_Transact<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Transact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Transact() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Transact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Transact(::grpc::ServerContext* context, const ::fraudservice::TransactRequest* request, ::fraudservice::TransactReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Transact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Transact() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Transact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Transact(::grpc::ServerContext* context, const ::fraudservice::TransactRequest* request, ::fraudservice::TransactReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTransact(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Transact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_Transact() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->Transact(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_Transact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Transact(::grpc::ServerContext* context, const ::fraudservice::TransactRequest* request, ::fraudservice::TransactReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Transact(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Transact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Transact() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::fraudservice::TransactRequest, ::fraudservice::TransactReply>(std::bind(&WithStreamedUnaryMethod_Transact<BaseClass>::StreamedTransact, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Transact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Transact(::grpc::ServerContext* context, const ::fraudservice::TransactRequest* request, ::fraudservice::TransactReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTransact(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fraudservice::TransactRequest,::fraudservice::TransactReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Transact<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Transact<Service > StreamedService;
};

}  // namespace fraudservice


#endif  // GRPC_fraud_5fservice_2eproto__INCLUDED
