# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fraud_service.proto',
  package='fraudservice',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x66raud_service.proto\x12\x0c\x66raudservice\"\x89\x02\n\x0fTransactRequest\x12\x15\n\rtransactionId\x18\x01 \x01(\t\x12\x11\n\tipAddress\x18\x02 \x01(\t\x12\x12\n\nmerchantId\x18\x03 \x01(\x03\x12\x0e\n\x06userId\x18\x04 \x01(\x03\x12\x13\n\x0buserAddress\x18\x05 \x01(\t\x12\x17\n\x0fshippingAddress\x18\x06 \x01(\t\x12\x0c\n\x04\x63ity\x18\x07 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x08 \x01(\t\x12\x0e\n\x06\x61mount\x18\t \x01(\x02\x12\x10\n\x08latitude\x18\n \x01(\x02\x12\x11\n\tlongitude\x18\x0b \x01(\x02\x12\x13\n\x0b\x63ookie_hash\x18\x0c \x01(\t\x12\x11\n\ttimeStamp\x18\r \x01(\x0c\"^\n\rTransactReply\x12\x14\n\x0cmessage_code\x18\x01 \x01(\x05\x12\x13\n\x0b\x66raud_score\x18\x02 \x01(\x02\x12\x12\n\nis_blocked\x18\x03 \x01(\x08\x12\x0e\n\x06reason\x18\x04 \x01(\t*?\n\x11TransactionStatus\x12\x12\n\x0eTRANSACTION_OK\x10\x00\x12\x16\n\x12TRANSACTION_FAILED\x10\x01\x32^\n\x12\x46raudDetectService\x12H\n\x08Transact\x12\x1d.fraudservice.TransactRequest\x1a\x1b.fraudservice.TransactReply\"\x00\x62\x06proto3')
)

_TRANSACTIONSTATUS = _descriptor.EnumDescriptor(
  name='TransactionStatus',
  full_name='fraudservice.TransactionStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRANSACTION_OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSACTION_FAILED', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=401,
  serialized_end=464,
)
_sym_db.RegisterEnumDescriptor(_TRANSACTIONSTATUS)

TransactionStatus = enum_type_wrapper.EnumTypeWrapper(_TRANSACTIONSTATUS)
TRANSACTION_OK = 0
TRANSACTION_FAILED = 1



_TRANSACTREQUEST = _descriptor.Descriptor(
  name='TransactRequest',
  full_name='fraudservice.TransactRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transactionId', full_name='fraudservice.TransactRequest.transactionId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipAddress', full_name='fraudservice.TransactRequest.ipAddress', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='merchantId', full_name='fraudservice.TransactRequest.merchantId', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='fraudservice.TransactRequest.userId', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userAddress', full_name='fraudservice.TransactRequest.userAddress', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shippingAddress', full_name='fraudservice.TransactRequest.shippingAddress', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='fraudservice.TransactRequest.city', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country', full_name='fraudservice.TransactRequest.country', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='fraudservice.TransactRequest.amount', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='fraudservice.TransactRequest.latitude', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='fraudservice.TransactRequest.longitude', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cookie_hash', full_name='fraudservice.TransactRequest.cookie_hash', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='fraudservice.TransactRequest.timeStamp', index=12,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=303,
)


_TRANSACTREPLY = _descriptor.Descriptor(
  name='TransactReply',
  full_name='fraudservice.TransactReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_code', full_name='fraudservice.TransactReply.message_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fraud_score', full_name='fraudservice.TransactReply.fraud_score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_blocked', full_name='fraudservice.TransactReply.is_blocked', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='fraudservice.TransactReply.reason', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=399,
)

DESCRIPTOR.message_types_by_name['TransactRequest'] = _TRANSACTREQUEST
DESCRIPTOR.message_types_by_name['TransactReply'] = _TRANSACTREPLY
DESCRIPTOR.enum_types_by_name['TransactionStatus'] = _TRANSACTIONSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactRequest = _reflection.GeneratedProtocolMessageType('TransactRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTREQUEST,
  '__module__' : 'fraud_service_pb2'
  # @@protoc_insertion_point(class_scope:fraudservice.TransactRequest)
  })
_sym_db.RegisterMessage(TransactRequest)

TransactReply = _reflection.GeneratedProtocolMessageType('TransactReply', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTREPLY,
  '__module__' : 'fraud_service_pb2'
  # @@protoc_insertion_point(class_scope:fraudservice.TransactReply)
  })
_sym_db.RegisterMessage(TransactReply)



_FRAUDDETECTSERVICE = _descriptor.ServiceDescriptor(
  name='FraudDetectService',
  full_name='fraudservice.FraudDetectService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=466,
  serialized_end=560,
  methods=[
  _descriptor.MethodDescriptor(
    name='Transact',
    full_name='fraudservice.FraudDetectService.Transact',
    index=0,
    containing_service=None,
    input_type=_TRANSACTREQUEST,
    output_type=_TRANSACTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRAUDDETECTSERVICE)

DESCRIPTOR.services_by_name['FraudDetectService'] = _FRAUDDETECTSERVICE

# @@protoc_insertion_point(module_scope)
